const deities = [
  {
    dietyName: "Abadar",
    category: "Gods of the Inner Sea",
    alignment: "LN",
    followerAlignments: ["LG", "LN", "LE"],
    divineFont: "harm/heal",
    domains: ["Cities", "Duty", "Earth", "Travel", "Wealth"],
    favoredWeapon: ["crossbow"],
  },
  {
    dietyName: "Asmodeus",
    category: "Gods of the Inner Sea",
    alignment: "LE",
    followerAlignments: ["LE"],
    divineFont: "harm",
    domains: ["Confidence", "Duty", "Fire", "Glyph", "Trickery", "Tyranny"],
    favoredWeapon: ["mace"],
  },
  {
    dietyName: "Calistria",
    category: "Gods of the Inner Sea",
    alignment: "CN",
    followerAlignments: ["CG", "CN", "CE"],
    divineFont: "harm/heal",
    domains: ["Pain", "Passion", "Secrecy", "Trickery"],
    favoredWeapon: ["whip"],
  },
  {
    dietyName: "Cayden Cailean",
    category: "Gods of the Inner Sea",
    alignment: "CG",
    followerAlignments: ["NG", "CG", "CN"],
    divineFont: "heal",
    domains: ["Cities", "Freedom", "Indulgence", "Might"],
    favoredWeapon: ["rapier"],
  },
  {
    dietyName: "Desna",
    category: "Gods of the Inner Sea",
    alignment: "CG",
    followerAlignments: ["NG", "CG", "CN"],
    divineFont: "heal",
    domains: ["Dreams", "Luck", "Moon", "Star", "Travel", "Void"],
    favoredWeapon: ["starknife"],
  },
  {
    dietyName: "Erastil",
    category: "Gods of the Inner Sea",
    alignment: "LG",
    followerAlignments: ["LG", "NG", "LN"],
    divineFont: "heal",
    domains: ["Duty", "Earth", "Family", "Nature", "Wealth"],
    favoredWeapon: ["longbow"],
  },
  {
    dietyName: "Gorum",
    category: "Gods of the Inner Sea",
    alignment: "CN",
    followerAlignments: ["CN", "CE"],
    divineFont: "harm/heal",
    domains: ["Confidence", "Destruction", "Might", "Zeal"],
    favoredWeapon: ["greatsw", "d"],
  },
  {
    dietyName: "Gozreh",
    category: "Gods of the Inner Sea",
    alignment: "N",
    followerAlignments: ["NG", "LN", "N", "CN", "NE"],
    divineFont: "heal",
    domains: ["Air", "Cold", "Lightning", "Nature", "Travel", "Water"],
    favoredWeapon: ["trident"],
  },
  {
    dietyName: "Iomedae",
    category: "Gods of the Inner Sea",
    alignment: "LG",
    followerAlignments: ["LG", "NG"],
    divineFont: "heal",
    domains: ["Confidence", "Duty", "Might", "Truth", "Zeal"],
    favoredWeapon: ["longsw", "d"],
  },
  {
    dietyName: "Irori",
    category: "Gods of the Inner Sea",
    alignment: "LN",
    followerAlignments: ["LG", "LN", "LE"],
    divineFont: "harm/heal",
    domains: ["Change", "Knowledge", "Might", "Perfection", "Truth", "Vigil"],
    favoredWeapon: ["fist"],
  },
  {
    dietyName: "Lamashtu",
    category: "Gods of the Inner Sea",
    alignment: "CE",
    followerAlignments: ["CE"],
    divineFont: "harm/heal",
    domains: ["Change", "Family", "Might", "Nightmares", "Trickery"],
    favoredWeapon: ["falchion"],
  },
  {
    dietyName: "Nethys",
    category: "Gods of the Inner Sea",
    alignment: "N",
    followerAlignments: ["NG", "LN", "N", "CN", "NE"],
    divineFont: "harm/heal",
    domains: ["Destruction", "Glyph", "Knowledge", "Magic", "Protection"],
    favoredWeapon: ["staff"],
  },
  {
    dietyName: "Norgorber",
    category: "Gods of the Inner Sea",
    alignment: "NE",
    followerAlignments: ["N (see entry)", "LE", "NE", "CE"],
    divineFont: "harm",
    domains: ["Death", "Secrecy", "Trickery", "Wealth"],
    favoredWeapon: ["sh", "tsw", "d"],
  },
  {
    dietyName: "Pharasma",
    category: "Gods of the Inner Sea",
    alignment: "N",
    followerAlignments: ["NG", "LN", "N"],
    divineFont: "heal",
    domains: ["Death", "Fate", "Healing", "Knowledge", "Soul", "Time", "Vigil"],
    favoredWeapon: ["dagger"],
  },
  {
    dietyName: "Rovagug",
    category: "Gods of the Inner Sea",
    alignment: "CE",
    followerAlignments: ["NE", "CE"],
    divineFont: "harm",
    domains: ["Air", "Destruction", "Earth", "Swarm", "Void", "Zeal"],
    favoredWeapon: ["greataxe"],
  },
  {
    dietyName: "Sarenrae",
    category: "Gods of the Inner Sea",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG"],
    divineFont: "heal",
    domains: ["Fire", "Healing", "Repose", "Sun", "Truth"],
    favoredWeapon: ["scimitar"],
  },
  {
    dietyName: "Shelyn",
    category: "Gods of the Inner Sea",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG"],
    divineFont: "heal",
    domains: ["Creation", "Family", "Passion", "Protection", "Repose"],
    favoredWeapon: ["glaive"],
  },
  {
    dietyName: "Torag",
    category: "Gods of the Inner Sea",
    alignment: "LG",
    followerAlignments: ["LG", "LN"],
    divineFont: "heal",
    domains: ["Creation", "Duty", "Earth", "Family", "Protection"],
    favoredWeapon: ["warhammer"],
  },
  {
    dietyName: "Urgathoa",
    category: "Gods of the Inner Sea",
    alignment: "NE",
    followerAlignments: ["LE", "NE", "CE"],
    divineFont: "harm",
    domains: [
      "Decay",
      "Indulgence",
      "Magic",
      "Might",
      "Plague",
      "Swarm",
      "Undeath",
    ],
    favoredWeapon: ["scythe"],
  },
  {
    dietyName: "Zon-Kuthon",
    category: "Gods of the Inner Sea",
    alignment: "LE",
    followerAlignments: ["LN", "LE", "NE"],
    divineFont: "harm",
    domains: ["Ambition", "Darkness", "Destruction", "Pain", "Void"],
    favoredWeapon: ["spiked chain"],
  },
  {
    dietyName: "Achaekek",
    category: "Other Gods",
    alignment: "LE",
    followerAlignments: ["LN", "LE", "NE"],
    divineFont: "harm",
    domains: ["Death", "Might", "Trickery", "Zeal"],
    favoredWeapon: ["sawtooth saber"],
  },
  {
    dietyName: "Adanye",
    category: "Other Gods",
    alignment: "LG",
    followerAlignments: ["LG", "NG", "CG", "LN"],
    divineFont: "heal",
    domains: ["Confidence", "Duty", "Family", "Fire", "Protection", "Repose"],
    favoredWeapon: ["claw", "kukri"],
  },
  {
    dietyName: "Ahriman",
    category: "Other Gods",
    alignment: "NE",
    followerAlignments: ["LE", "NE", "CE"],
    divineFont: "harm",
    domains: ["Darkness", "Death", "Destruction", "Trickery"],
    favoredWeapon: ["whip"],
  },
  {
    dietyName: "Alseta",
    category: "Other Gods",
    alignment: "LN",
    followerAlignments: ["LG", "LN", "N"],
    divineFont: "heal",
    domains: ["Change", "Magic", "Protection", "Time"],
    favoredWeapon: ["dagger"],
  },
  {
    dietyName: "Apsu",
    category: "Other Gods",
    alignment: "LG",
    followerAlignments: ["LG", "NG", "CG"],
    divineFont: "heal",
    domains: ["Creation", "Protection", "Travel", "Wyrmkin"],
    favoredWeapon: ["jaws", "staff"],
  },
  {
    dietyName: "Arazni",
    category: "Other Gods",
    alignment: "NE",
    followerAlignments: ["CG", "LN", "N", "CN", "NE"],
    divineFont: "harm",
    domains: ["Confidence", "Freedom", "Pain", "Protection", "Sorrow"],
    favoredWeapon: ["rapier"],
  },
  {
    dietyName: "Balumbdar",
    category: "Other Gods",
    alignment: "N",
    followerAlignments: ["NG", "N", "NE"],
    divineFont: "heal",
    domains: ["Might", "Nature", "Perfection", "Protection"],
    favoredWeapon: ["greatclub"],
  },
  {
    dietyName: "Besmara",
    category: "Other Gods",
    alignment: "CN",
    followerAlignments: ["CG", "CN", "CE"],
    divineFont: "harm/heal",
    domains: ["Destruction", "Trickery", "Water", "Wealth"],
    favoredWeapon: ["rapier"],
  },
  {
    dietyName: "Brigh",
    category: "Other Gods",
    alignment: "N",
    followerAlignments: ["NG", "LN", "N", "CN", "NE"],
    divineFont: "harm/heal",
    domains: ["Creation", "Earth", "Fire", "Knowledge", "Time"],
    favoredWeapon: ["light hammer"],
  },
  {
    dietyName: "Casandalee",
    category: "Other Gods",
    alignment: "N",
    followerAlignments: ["NG", "LN", "N", "CN", "NE"],
    divineFont: "harm/heal",
    domains: [
      "Ambition",
      "Creation",
      "Freedom",
      "Knowledge",
      "Lightning",
      "Perfection",
    ],
    favoredWeapon: ["polytool"],
  },
  {
    dietyName: "Chaldira",
    category: "Other Gods",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG"],
    divineFont: "heal",
    domains: ["Confidence", "Luck", "Trickery", "Zeal"],
    favoredWeapon: ["sh", "tsw", "d"],
  },
  {
    dietyName: "Conqueror Worm",
    category: "Other Gods",
    alignment: "No Alignment",
    followerAlignments: ["LE", "NE", "CE"],
    divineFont: "harm",
    domains: ["Ambition", "Secrecy", "Trickery", "Tyranny"],
    favoredWeapon: ["dagger"],
  },
  {
    dietyName: "Dahak",
    category: "Other Gods",
    alignment: "CE",
    followerAlignments: ["CE"],
    divineFont: "harm",
    domains: ["Destruction", "Fire", "Wyrmkin", "Zeal"],
    favoredWeapon: ["jaws", "whip"],
  },
  {
    dietyName: "Erecura",
    category: "Other Gods",
    alignment: "LN",
    followerAlignments: ["LG", "LN", "N"],
    divineFont: "harm/heal",
    domains: ["Fate", "Secrecy", "Trickery", "Truth"],
    favoredWeapon: ["light mace"],
  },
  {
    dietyName: "Followers of Fate",
    category: "Other Gods",
    alignment: "LN",
    followerAlignments: ["LG", "LN", "LE"],
    divineFont: "harm/heal",
    domains: ["Family", "Fate", "Knowledge", "Truth"],
    favoredWeapon: ["shears"],
  },
  {
    dietyName: "Gendowyn",
    category: "Other Gods",
    alignment: "CN",
    followerAlignments: ["CG", "N", "CN", "CE"],
    divineFont: "heal",
    domains: ["Earth", "Family", "Luck", "Nature"],
    favoredWeapon: ["whip"],
  },
  {
    dietyName: "Ghlaunder",
    category: "Other Gods",
    alignment: "CE",
    followerAlignments: ["NE", "CE"],
    divineFont: "harm",
    domains: ["Air", "Decay", "Plague", "Swarm"],
    favoredWeapon: ["spear"],
  },
  {
    dietyName: "Grandmother Spider",
    category: "Other Gods",
    alignment: "N",
    followerAlignments: ["NG", "CG", "N", "CN"],
    divineFont: "harm/heal",
    domains: ["Change", "Creation", "Darkness", "Family", "Fate", "Trickery"],
    favoredWeapon: ["bola"],
  },
  {
    dietyName: "Green Man",
    category: "Other Gods",
    alignment: "N",
    followerAlignments: ["NG", "N", "NE"],
    divineFont: "heal",
    domains: ["Healing", "Might", "Nature", "Protection"],
    favoredWeapon: ["sickle"],
  },
  {
    dietyName: "Groetus",
    category: "Other Gods",
    alignment: "CN",
    followerAlignments: ["CN", "CE"],
    divineFont: "harm",
    domains: ["Darkness", "Decay", "Destruction", "Nightmares", "Void"],
    favoredWeapon: ["war flail"],
  },
  {
    dietyName: "Gyronna",
    category: "Other Gods",
    alignment: "CE",
    followerAlignments: ["NE", "CE"],
    divineFont: "harm",
    domains: ["Ambition", "Nightmares", "Pain", "Zeal"],
    favoredWeapon: ["dagger"],
  },
  {
    dietyName: "Hanspur",
    category: "Other Gods",
    alignment: "CN",
    followerAlignments: ["CG", "N", "CN", "CE"],
    divineFont: "harm",
    domains: ["Death", "Travel", "Water", "Wealth"],
    favoredWeapon: ["trident"],
  },
  {
    dietyName: "Jaidi",
    category: "Other Gods",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "N"],
    divineFont: "heal",
    domains: ["Family", "Might", "Nature", "Sun"],
    favoredWeapon: ["scythe"],
  },
  {
    dietyName: "Kalekot",
    category: "Other Gods",
    alignment: "CN",
    followerAlignments: ["CG", "N", "CN", "CE"],
    divineFont: "harm",
    domains: [
      "Darkness",
      "Death",
      "Nature",
      "Nightmares",
      "Secrecy",
      "Wyrmkin",
    ],
    favoredWeapon: ["jaws", "dagger"],
  },
  {
    dietyName: "Kazutal",
    category: "Other Gods",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG"],
    divineFont: "heal",
    domains: ["Cities", "Family", "Freedom", "Might", "Protection"],
    favoredWeapon: ["machete"],
  },
  {
    dietyName: "Kitumu",
    category: "Other Gods",
    alignment: "CE",
    followerAlignments: ["NE", "CE"],
    divineFont: "harm",
    domains: ["Destruction", "Indulgence", "Nightmares", "Swarm"],
    favoredWeapon: ["dagger"],
  },
  {
    dietyName: "Kurgess",
    category: "Other Gods",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG", "N"],
    divineFont: "heal",
    domains: ["Ambition", "Might", "Truth", "Zeal"],
    favoredWeapon: ["javelin"],
  },
  {
    dietyName: "Lissala",
    category: "Other Gods",
    alignment: "LE",
    followerAlignments: ["LN", "LE"],
    divineFont: "harm",
    domains: ["Fate", "Glyph", "Magic", "Toil"],
    favoredWeapon: ["whip"],
  },
  {
    dietyName: "Lubaiko",
    category: "Other Gods",
    alignment: "CN",
    followerAlignments: ["CG", "N", "CN", "CE"],
    divineFont: "harm/heal",
    domains: ["Ambition", "Change", "Destruction", "Fire", "Lightning", "Zeal"],
    favoredWeapon: ["longspear"],
  },
  {
    dietyName: "Mazludeh",
    category: "Other Gods",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG"],
    divineFont: "heal",
    domains: ["Cities", "Duty", "Family", "Knowledge", "Nature", "Perfection"],
    favoredWeapon: ["shield boss"],
  },
  {
    dietyName: "Milani",
    category: "Other Gods",
    alignment: "CG",
    followerAlignments: ["NG", "CG", "CN"],
    divineFont: "heal",
    domains: ["Change", "Destruction", "Freedom", "Zeal"],
    favoredWeapon: ["m", "ningstar"],
  },
  {
    dietyName: "Naderi",
    category: "Other Gods",
    alignment: "N",
    followerAlignments: ["NG", "N", "NE"],
    divineFont: "harm",
    domains: ["Death", "Passion", "Sorrow", "Water"],
    favoredWeapon: ["dagger"],
  },
  {
    dietyName: "Nivi Rhombodazzle",
    category: "Other Gods",
    alignment: "N",
    followerAlignments: ["NG", "LN", "N", "CN"],
    divineFont: "harm/heal",
    domains: ["Confidence", "Earth", "Family", "Luck", "Trickery", "Wealth"],
    favoredWeapon: ["light hammer"],
  },
  {
    dietyName: "Nocticula",
    category: "Other Gods",
    alignment: "CN",
    followerAlignments: ["CG", "N", "CN"],
    divineFont: "heal",
    domains: ["Change", "Creation", "Darkness", "Travel"],
    favoredWeapon: ["dagger"],
  },
  {
    dietyName: "Ravithra",
    category: "Other Gods",
    alignment: "LN",
    followerAlignments: ["LG", "LN", "N", "LE"],
    divineFont: "harm",
    domains: ["Ambition", "Fate", "Naga", "Sorrow", "Soul", "Truth"],
    favoredWeapon: ["jaws", "light mace"],
  },
  {
    dietyName: "Sivanah",
    category: "Other Gods",
    alignment: "N",
    followerAlignments: ["NG", "LN", "N", "CN", "NE"],
    divineFont: "harm/heal",
    domains: ["Delirium", "Glyph", "Magic", "Secrecy", "Trickery"],
    favoredWeapon: ["bladed scarf"],
  },
  {
    dietyName: "Thamir",
    category: "Other Gods",
    alignment: "CE",
    followerAlignments: ["NE", "CE"],
    divineFont: "harm",
    domains: ["Ambition", "Confidence", "Trickery", "Wealth"],
    favoredWeapon: ["dagger"],
  },
  {
    dietyName: "Uvuko",
    category: "Other Gods",
    alignment: "CG",
    followerAlignments: ["NG", "CG", "N", "CN"],
    divineFont: "heal",
    domains: ["Air", "Change", "Cold", "Creation", "Healing", "Wyrmkin"],
    favoredWeapon: ["maul"],
  },
  {
    dietyName: "Walkena",
    category: "Other Gods",
    alignment: "LE",
    followerAlignments: ["LN", "LE"],
    divineFont: "harm",
    domains: ["Duty", "Family", "Fire", "Freedom", "Sun", "Tyranny"],
    favoredWeapon: ["spear"],
  },
  {
    dietyName: "Ydersius",
    category: "Other Gods",
    alignment: "CE",
    followerAlignments: ["LE", "NE", "CE"],
    divineFont: "harm",
    domains: ["Ambition", "Indulgence", "Might", "Zeal"],
    favoredWeapon: ["dagger"],
  },
  {
    dietyName: "Zyphus",
    category: "Other Gods",
    alignment: "NE",
    followerAlignments: ["NE", "CE"],
    divineFont: "harm",
    domains: ["Death", "Sorrow", "Soul", "Undeath"],
    favoredWeapon: ["pick"],
  },
  {
    dietyName: "Anubis",
    category: "Ancient Osirian Gods",
    alignment: "LN",
    followerAlignments: ["LG", "LN", "N"],
    divineFont: "harm/heal",
    domains: ["Death", "Protection", "Soul", "Vigil"],
    favoredWeapon: ["flail"],
  },
  {
    dietyName: "Bastet",
    category: "Ancient Osirian Gods",
    alignment: "CN",
    followerAlignments: ["CG", "N", "CN"],
    divineFont: "heal",
    domains: ["Nature", "Passion", "Protection", "Trickery"],
    favoredWeapon: ["claw", "tekko-kagi"],
  },
  {
    dietyName: "Bes",
    category: "Ancient Osirian Gods",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG"],
    divineFont: "heal",
    domains: ["Earth", "Family", "Luck", "Protection"],
    favoredWeapon: ["mambele"],
  },
  {
    dietyName: "Hathor",
    category: "Ancient Osirian Gods",
    alignment: "CG",
    followerAlignments: ["NG", "CG"],
    divineFont: "heal",
    domains: ["Family", "Passion", "Sun", "Wealth"],
    favoredWeapon: ["sh", "tsw", "d"],
  },
  {
    dietyName: "Horus",
    category: "Ancient Osirian Gods",
    alignment: "LN",
    followerAlignments: ["LG", "NG", "LN", "N"],
    divineFont: "heal",
    domains: ["Air", "Moon", "Protection", "Sun"],
    favoredWeapon: ["khopesh"],
  },
  {
    dietyName: "Isis",
    category: "Ancient Osirian Gods",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG"],
    divineFont: "heal",
    domains: ["Family", "Healing", "Magic", "Passion"],
    favoredWeapon: ["staff"],
  },
  {
    dietyName: "Ma'at",
    category: "Ancient Osirian Gods",
    alignment: "LN",
    followerAlignments: ["LG", "LN", "N"],
    divineFont: "heal",
    domains: ["Knowledge", "Protection", "Star", "Truth"],
    favoredWeapon: ["starknife"],
  },
  {
    dietyName: "Osiris",
    category: "Ancient Osirian Gods",
    alignment: "LG",
    followerAlignments: ["LG", "NG"],
    divineFont: "heal",
    domains: ["Change", "Healing", "Nature", "Soul"],
    favoredWeapon: ["flail"],
  },
  {
    dietyName: "Ra",
    category: "Ancient Osirian Gods",
    alignment: "LN",
    followerAlignments: ["LG", "LN", "N"],
    divineFont: "heal",
    domains: ["Fire", "Nature", "Sun", "Time"],
    favoredWeapon: ["spear"],
  },
  {
    dietyName: "Sekhmet",
    category: "Ancient Osirian Gods",
    alignment: "CN",
    followerAlignments: ["CG", "N", "CN", "CE"],
    divineFont: "harm/heal",
    domains: ["Destruction", "Healing", "Indulgence", "Might"],
    favoredWeapon: ["claw", "battle axe"],
  },
  {
    dietyName: "Selket",
    category: "Ancient Osirian Gods",
    alignment: "CG",
    followerAlignments: ["NG", "CG", "CN"],
    divineFont: "heal",
    domains: ["Healing", "Magic", "Nature", "Protection"],
    favoredWeapon: ["whip"],
  },
  {
    dietyName: "Sobek",
    category: "Ancient Osirian Gods",
    alignment: "CN",
    followerAlignments: ["CG", "N", "CN", "CE"],
    divineFont: "harm/heal",
    domains: ["Might", "Protection", "Water", "Wyrmkin"],
    favoredWeapon: ["falchion"],
  },
  {
    dietyName: "Thoth",
    category: "Ancient Osirian Gods",
    alignment: "LN",
    followerAlignments: ["LG", "LN", "N"],
    divineFont: "harm/heal",
    domains: ["Glyph", "Knowledge", "Magic", "Moon"],
    favoredWeapon: ["sickle"],
  },
  {
    dietyName: "Wadjet",
    category: "Ancient Osirian Gods",
    alignment: "LG",
    followerAlignments: ["LG", "NG"],
    divineFont: "heal",
    domains: ["Protection", "Travel", "Water", "Zeal"],
    favoredWeapon: ["light mace"],
  },
  {
    dietyName: "Baalzebul",
    category: "Archdevils",
    alignment: "LE",
    followerAlignments: ["LE"],
    divineFont: "harm",
    domains: ["Air", "Ambition", "Magic", "Trickery"],
    favoredWeapon: ["spear"],
  },
  {
    dietyName: "Barbatos",
    category: "Archdevils",
    alignment: "LE",
    followerAlignments: ["LE"],
    divineFont: "harm",
    domains: ["Magic", "Nature", "Travel", "Tyranny"],
    favoredWeapon: ["staff"],
  },
  {
    dietyName: "Belial",
    category: "Archdevils",
    alignment: "LE",
    followerAlignments: ["LE"],
    divineFont: "harm",
    domains: ["Change", "Passion", "Trickery", "Zeal"],
    favoredWeapon: ["ranseur"],
  },
  {
    dietyName: "Dispater",
    category: "Archdevils",
    alignment: "LE",
    followerAlignments: ["LN", "LE"],
    divineFont: "harm",
    domains: ["Cities", "Confidence", "Duty", "Tyranny"],
    favoredWeapon: ["mace"],
  },
  {
    dietyName: "Geryon",
    category: "Archdevils",
    alignment: "LE",
    followerAlignments: ["LE"],
    divineFont: "harm",
    domains: ["Might", "Truth", "Water", "Wyrmkin"],
    favoredWeapon: ["war flail"],
  },
  {
    dietyName: "Mammon",
    category: "Archdevils",
    alignment: "LE",
    followerAlignments: ["LE"],
    divineFont: "harm",
    domains: ["Ambition", "Creation", "Toil", "Wealth"],
    favoredWeapon: ["spear"],
  },
  {
    dietyName: "Mephistopheles",
    category: "Archdevils",
    alignment: "LE",
    followerAlignments: ["LE"],
    divineFont: "harm",
    domains: ["Glyph", "Knowledge", "Secrecy", "Tyranny"],
    favoredWeapon: ["trident"],
  },
  {
    dietyName: "Moloch",
    category: "Archdevils",
    alignment: "LE",
    followerAlignments: ["LE"],
    divineFont: "harm",
    domains: ["Destruction", "Duty", "Fire", "Might"],
    favoredWeapon: ["whip"],
  },
  {
    dietyName: "Abraxas",
    category: "Demon Lords",
    alignment: "CE",
    followerAlignments: ["NE", "CE"],
    divineFont: "harm",
    domains: ["Destruction", "Knowledge", "Magic", "Wyrmkin"],
    favoredWeapon: ["whip"],
  },
  {
    dietyName: "Angazhan",
    category: "Demon Lords",
    alignment: "CE",
    followerAlignments: ["CE"],
    divineFont: "harm",
    domains: [
      "Destruction",
      "Indulgence",
      "Might",
      "Nature",
      "Tyranny",
      "Zeal",
    ],
    favoredWeapon: ["fist", "spear"],
  },
  {
    dietyName: "Baphomet",
    category: "Demon Lords",
    alignment: "CE",
    followerAlignments: ["CN", "CE"],
    divineFont: "harm/heal",
    domains: ["Indulgence", "Might", "Secrecy", "Zeal"],
    favoredWeapon: ["glaive"],
  },
  {
    dietyName: "Cyth-V'sug",
    category: "Demon Lords",
    alignment: "CE",
    followerAlignments: ["CE"],
    divineFont: "harm",
    domains: ["Change", "Decay", "Nature", "Plague"],
    favoredWeapon: ["scimitar"],
  },
  {
    dietyName: "Dagon",
    category: "Demon Lords",
    alignment: "CE",
    followerAlignments: ["CN", "CE"],
    divineFont: "harm",
    domains: ["Change", "Destruction", "Water", "Zeal"],
    favoredWeapon: ["trident"],
  },
  {
    dietyName: "Gogunta",
    category: "Demon Lords",
    alignment: "CE",
    followerAlignments: ["CE"],
    divineFont: "harm",
    domains: ["Indulgence", "Might", "Tyranny", "Water"],
    favoredWeapon: ["whip"],
  },
  {
    dietyName: "Kabriri",
    category: "Demon Lords",
    alignment: "CE",
    followerAlignments: ["NE", "CE"],
    divineFont: "harm",
    domains: ["Indulgence", "Knowledge", "Undeath", "Vigil"],
    favoredWeapon: ["jaws", "flail"],
  },
  {
    dietyName: "Kostchtchie",
    category: "Demon Lords",
    alignment: "CE",
    followerAlignments: ["NE", "CE"],
    divineFont: "harm",
    domains: ["Cold", "Destruction", "Might", "Zeal"],
    favoredWeapon: ["warhammer"],
  },
  {
    dietyName: "Nurgal",
    category: "Demon Lords",
    alignment: "CE",
    followerAlignments: ["NE", "CE"],
    divineFont: "harm",
    domains: ["Destruction", "Dust", "Fire", "Sun"],
    favoredWeapon: ["mace"],
  },
  {
    dietyName: "Pazuzu",
    category: "Demon Lords",
    alignment: "CE",
    followerAlignments: ["CE"],
    divineFont: "harm",
    domains: ["Air", "Swarm", "Trickery", "Tyranny"],
    favoredWeapon: ["longsw", "d"],
  },
  {
    dietyName: "Shax",
    category: "Demon Lords",
    alignment: "CE",
    followerAlignments: ["NE", "CE"],
    divineFont: "harm",
    domains: ["Ambition", "Death", "Pain", "Trickery"],
    favoredWeapon: ["dagger"],
  },
  {
    dietyName: "Sifkesh",
    category: "Demon Lords",
    alignment: "CE",
    followerAlignments: ["NE", "CE"],
    divineFont: "harm",
    domains: ["Nightmares", "Pain", "Sorrow", "Trickery"],
    favoredWeapon: ["war raz", ""],
  },
  {
    dietyName: "Treerazer",
    category: "Demon Lords",
    alignment: "CE",
    followerAlignments: ["NE", "CE"],
    divineFont: "harm/heal",
    domains: ["Destruction", "Nature", "Nightmares", "Tyranny"],
    favoredWeapon: ["battle axe"],
  },
  {
    dietyName: "Zevgavizeb",
    category: "Demon Lords",
    alignment: "CE",
    followerAlignments: ["NE", "CE"],
    divineFont: "harm",
    domains: ["Destruction", "Might", "Nature", "Wyrmkin"],
    favoredWeapon: ["spiked gauntlet"],
  },
  {
    dietyName: "Zura",
    category: "Demon Lords",
    alignment: "CE",
    followerAlignments: ["NE", "CE"],
    divineFont: "harm",
    domains: ["Delirium", "Indulgence", "Nightmares", "Undeath"],
    favoredWeapon: ["rapier"],
  },
  {
    dietyName: "Angradd",
    category: "Dwarven Gods",
    alignment: "LG",
    followerAlignments: ["LG", "LN"],
    divineFont: "heal",
    domains: ["Fate", "Fire", "Protection", "Zeal"],
    favoredWeapon: ["greataxe"],
  },
  {
    dietyName: "Bolka",
    category: "Dwarven Gods",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG"],
    divineFont: "heal",
    domains: ["Confidence", "Family", "Healing", "Passion"],
    favoredWeapon: ["mace"],
  },
  {
    dietyName: "Dranngvit",
    category: "Dwarven Gods",
    alignment: "LN",
    followerAlignments: ["LN", "LE"],
    divineFont: "harm/heal",
    domains: ["Knowledge", "Might", "Travel", "Vigil"],
    favoredWeapon: ["light pick"],
  },
  {
    dietyName: "Droskar",
    category: "Dwarven Gods",
    alignment: "NE",
    followerAlignments: ["LE", "NE", "CE"],
    divineFont: "harm",
    domains: [
      "Ambition",
      "Duty",
      "Earth",
      "Fire",
      "Toil",
      "Trickery",
      "Tyranny",
    ],
    favoredWeapon: ["light hammer"],
  },
  {
    dietyName: "Folgrit",
    category: "Dwarven Gods",
    alignment: "LG",
    followerAlignments: ["LG", "NG", "LN"],
    divineFont: "heal",
    domains: ["Cities", "Family", "Protection", "Repose"],
    favoredWeapon: ["staff"],
  },
  {
    dietyName: "Grundinnar",
    category: "Dwarven Gods",
    alignment: "LG",
    followerAlignments: ["LG", "NG"],
    divineFont: "heal",
    domains: ["Confidence", "Family", "Protection", "Truth"],
    favoredWeapon: ["light hammer"],
  },
  {
    dietyName: "Kols",
    category: "Dwarven Gods",
    alignment: "LN",
    followerAlignments: ["LG", "LN"],
    divineFont: "harm/heal",
    domains: ["Duty", "Knowledge", "Might", "Truth"],
    favoredWeapon: ["light hammer"],
  },
  {
    dietyName: "Magrim",
    category: "Dwarven Gods",
    alignment: "LN",
    followerAlignments: ["LG", "LN", "N"],
    divineFont: "heal",
    domains: ["Death", "Duty", "Fate", "Glyph"],
    favoredWeapon: ["warhammer"],
  },
  {
    dietyName: "Trudd",
    category: "Dwarven Gods",
    alignment: "NG",
    followerAlignments: ["LG", "NG"],
    divineFont: "heal",
    domains: ["Confidence", "Duty", "Might", "Protection"],
    favoredWeapon: ["warhammer"],
  },
  {
    dietyName: "Count Ranalc",
    category: "Eldest",
    alignment: "CN",
    followerAlignments: ["CG", "N", "CN", "CE"],
    divineFont: "harm/heal",
    domains: ["Confidence", "Darkness", "Sorrow", "Travel"],
    favoredWeapon: ["rapier"],
  },
  {
    dietyName: "Imbrex",
    category: "Eldest",
    alignment: "LN",
    followerAlignments: ["LN", "N", "LE"],
    divineFont: "harm/heal",
    domains: ["Dreams", "Earth", "Family", "Might"],
    favoredWeapon: ["war flail"],
  },
  {
    dietyName: "Magdh",
    category: "Eldest",
    alignment: "LN",
    followerAlignments: ["LN", "N"],
    divineFont: "harm/heal",
    domains: ["Fate", "Glyph", "Knowledge", "Truth"],
    favoredWeapon: ["scythe"],
  },
  {
    dietyName: "Ng",
    category: "Eldest",
    alignment: "N",
    followerAlignments: ["N"],
    divineFont: "harm/heal",
    domains: ["Knowledge", "Magic", "Secrecy", "Travel"],
    favoredWeapon: ["gauntlet"],
  },
  {
    dietyName: "Ragadahn",
    category: "Eldest",
    alignment: "CE",
    followerAlignments: ["CN", "NE", "CE"],
    divineFont: "harm/heal",
    domains: ["Destruction", "Vigil", "Water", "Wyrmkin"],
    favoredWeapon: ["whip"],
  },
  {
    dietyName: "Shyka",
    category: "Eldest",
    alignment: "N",
    followerAlignments: ["NG", "LN", "N", "CN", "NE"],
    divineFont: "harm/heal",
    domains: ["Decay", "Delirium", "Fate", "Time"],
    favoredWeapon: ["light mace"],
  },
  {
    dietyName: "The Green Mother",
    category: "Eldest",
    alignment: "NE",
    followerAlignments: ["NE", "CE"],
    divineFont: "harm/heal",
    domains: ["Decay", "Indulgence", "Nature", "Passion"],
    favoredWeapon: ["sickle"],
  },
  {
    dietyName: "The Lantern King",
    category: "Eldest",
    alignment: "CN",
    followerAlignments: ["CN", "CE"],
    divineFont: "harm/heal",
    domains: ["Change", "Delirium", "Passion", "Trickery"],
    favoredWeapon: ["dagger"],
  },
  {
    dietyName: "The Lost Prince",
    category: "Eldest",
    alignment: "N",
    followerAlignments: ["NG", "N"],
    divineFont: "harm/heal",
    domains: ["Knowledge", "Repose", "Sorrow", "Vigil"],
    favoredWeapon: ["staff"],
  },
  {
    dietyName: "Atreia",
    category: "Elemental Lords",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG", "N"],
    divineFont: "heal",
    domains: ["Fire", "Healing", "Protection", "Sun"],
    favoredWeapon: ["katar"],
  },
  {
    dietyName: "Ayrzul",
    category: "Elemental Lords",
    alignment: "NE",
    followerAlignments: ["N", "LE", "NE", "CE"],
    divineFont: "harm",
    domains: ["Destruction", "Earth", "Might", "Secrecy"],
    favoredWeapon: ["m", "ningstar"],
  },
  {
    dietyName: "Hshurha",
    category: "Elemental Lords",
    alignment: "NE",
    followerAlignments: ["N", "LE", "NE", "CE"],
    divineFont: "harm",
    domains: ["Air", "Cold", "Destruction", "Dust"],
    favoredWeapon: ["longbow"],
  },
  {
    dietyName: "Kelizandri",
    category: "Elemental Lords",
    alignment: "NE",
    followerAlignments: ["N", "LE", "NE", "CE"],
    divineFont: "harm",
    domains: ["Destruction", "Nightmares", "Travel", "Water"],
    favoredWeapon: ["trident"],
  },
  {
    dietyName: "Lysianassa",
    category: "Elemental Lords",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG", "N"],
    divineFont: "heal",
    domains: ["Change", "Fate", "Nature", "Water"],
    favoredWeapon: ["spear"],
  },
  {
    dietyName: "Ranginori",
    category: "Elemental Lords",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG", "N"],
    divineFont: "heal",
    domains: ["Air", "Freedom", "Lightning", "Travel"],
    favoredWeapon: ["whip"],
  },
  {
    dietyName: "Sairazul",
    category: "Elemental Lords",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG", "N"],
    divineFont: "heal",
    domains: ["Earth", "Family", "Toil", "Wealth"],
    favoredWeapon: ["pick"],
  },
  {
    dietyName: "Ymeri",
    category: "Elemental Lords",
    alignment: "NE",
    followerAlignments: ["N", "LE", "NE", "CE"],
    divineFont: "harm",
    domains: ["Destruction", "Dust", "Fire", "Zeal"],
    favoredWeapon: ["longsw", "d"],
  },
  {
    dietyName: "Findeladlara",
    category: "Elven Gods",
    alignment: "CG",
    followerAlignments: ["NG", "CG", "N", "CN"],
    divineFont: "heal",
    domains: ["Cities", "Creation", "Family", "Star"],
    favoredWeapon: ["staff"],
  },
  {
    dietyName: "Ketephys",
    category: "Elven Gods",
    alignment: "CG",
    followerAlignments: ["NG", "CG"],
    divineFont: "heal",
    domains: ["Darkness", "Moon", "Nature", "Secrecy"],
    favoredWeapon: ["longbow"],
  },
  {
    dietyName: "Yuelral",
    category: "Elven Gods",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG", "N"],
    divineFont: "heal",
    domains: ["Creation", "Earth", "Knowledge", "Magic"],
    favoredWeapon: ["dagger"],
  },
  {
    dietyName: "Andoletta",
    category: "Empyreal Lords",
    alignment: "LG",
    followerAlignments: ["LG", "NG"],
    divineFont: "heal",
    domains: ["Family", "Knowledge", "Protection", "Sorrow"],
    favoredWeapon: ["staff"],
  },
  {
    dietyName: "Arshea",
    category: "Empyreal Lords",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG"],
    divineFont: "heal",
    domains: ["Confidence", "Freedom", "Passion", "Perfection"],
    favoredWeapon: ["flail"],
  },
  {
    dietyName: "Ashava",
    category: "Empyreal Lords",
    alignment: "CG",
    followerAlignments: ["NG", "CG"],
    divineFont: "heal",
    domains: ["Darkness", "Moon", "Repose", "Soul"],
    favoredWeapon: ["bladed scarf"],
  },
  {
    dietyName: "Black Butterfly",
    category: "Empyreal Lords",
    alignment: "CG",
    followerAlignments: ["NG", "CG"],
    divineFont: "heal",
    domains: ["Freedom", "Secrecy", "Star", "Void"],
    favoredWeapon: ["starknife"],
  },
  {
    dietyName: "Cernunnos",
    category: "Empyreal Lords",
    alignment: "CG",
    followerAlignments: ["LG", "NG", "CG"],
    divineFont: "heal",
    domains: ["Lightning", "Nature", "Passion", "Zeal"],
    favoredWeapon: ["longbow"],
  },
  {
    dietyName: "Dammerich",
    category: "Empyreal Lords",
    alignment: "LG",
    followerAlignments: ["LG"],
    divineFont: "harm/heal",
    domains: ["Death", "Duty", "Truth", "Vigil"],
    favoredWeapon: ["greataxe"],
  },
  {
    dietyName: "Eritrice",
    category: "Empyreal Lords",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG"],
    divineFont: "heal",
    domains: ["Confidence", "Glyph", "Knowledge", "Truth"],
    favoredWeapon: ["dagger"],
  },
  {
    dietyName: "Falayna",
    category: "Empyreal Lords",
    alignment: "LG",
    followerAlignments: ["LG", "NG", "CG"],
    divineFont: "heal",
    domains: ["Creation", "Freedom", "Might", "Wealth"],
    favoredWeapon: ["longsw", "d"],
  },
  {
    dietyName: "Halcamora",
    category: "Empyreal Lords",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "N"],
    divineFont: "heal",
    domains: ["Indulgence", "Luck", "Nature", "Swarm"],
    favoredWeapon: ["club"],
  },
  {
    dietyName: "Irez",
    category: "Empyreal Lords",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG", "N"],
    divineFont: "heal",
    domains: ["Fate", "Glyph", "Luck", "Magic"],
    favoredWeapon: ["dart"],
  },
  {
    dietyName: "Jaidz",
    category: "Empyreal Lords",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG", "N"],
    divineFont: "heal",
    domains: ["Confidence", "Nightmares", "Protection", "Travel"],
    favoredWeapon: ["sh", "tsw", "d"],
  },
  {
    dietyName: "Korada",
    category: "Empyreal Lords",
    alignment: "NG",
    followerAlignments: ["NG", "N"],
    divineFont: "heal",
    domains: ["Change", "Healing", "Magic", "Protection"],
    favoredWeapon: ["fist"],
  },
  {
    dietyName: "Lymnieris",
    category: "Empyreal Lords",
    alignment: "LG",
    followerAlignments: ["LG", "NG", "CG"],
    divineFont: "heal",
    domains: ["Change", "Passion", "Protection", "Repose"],
    favoredWeapon: ["longsw", "d"],
  },
  {
    dietyName: "Pulura",
    category: "Empyreal Lords",
    alignment: "CG",
    followerAlignments: ["NG", "CG"],
    divineFont: "heal",
    domains: ["Cold", "Darkness", "Sorrow", "Star"],
    favoredWeapon: ["sling"],
  },
  {
    dietyName: "Ragathiel",
    category: "Empyreal Lords",
    alignment: "LG",
    followerAlignments: ["LG"],
    divineFont: "harm/heal",
    domains: ["Destruction", "Duty", "Fire", "Zeal"],
    favoredWeapon: ["bastard sw", "d"],
  },
  {
    dietyName: "Shei",
    category: "Empyreal Lords",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG"],
    divineFont: "heal",
    domains: ["Family", "Freedom", "Healing", "Perfection"],
    favoredWeapon: ["sickle"],
  },
  {
    dietyName: "Soralyon",
    category: "Empyreal Lords",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG", "N"],
    divineFont: "heal",
    domains: ["Creation", "Earth", "Magic", "Protection"],
    favoredWeapon: ["pick"],
  },
  {
    dietyName: "Tanagaar",
    category: "Empyreal Lords",
    alignment: "LG",
    followerAlignments: ["LG", "LN"],
    divineFont: "heal",
    domains: ["Darkness", "Duty", "Nature", "Zeal"],
    favoredWeapon: ["kukri"],
  },
  {
    dietyName: "Vildeis",
    category: "Empyreal Lords",
    alignment: "LG",
    followerAlignments: ["LG"],
    divineFont: "harm/heal",
    domains: ["Duty", "Pain", "Sorrow", "Zeal"],
    favoredWeapon: ["dagger"],
  },
  {
    dietyName: "Winlas",
    category: "Empyreal Lords",
    alignment: "LG",
    followerAlignments: ["LG", "NG", "LN"],
    divineFont: "heal",
    domains: ["Glyph", "Knowledge", "Protection", "Vigil"],
    favoredWeapon: ["mace"],
  },
  {
    dietyName: "Ylimancha",
    category: "Empyreal Lords",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG", "N"],
    divineFont: "heal",
    domains: ["Air", "Nature", "Travel", "Water"],
    favoredWeapon: ["longbow"],
  },
  {
    dietyName: "Zohls",
    category: "Empyreal Lords",
    alignment: "LG",
    followerAlignments: ["LG", "NG", "LN"],
    divineFont: "heal",
    domains: ["Ambition", "Cities", "Knowledge", "Truth"],
    favoredWeapon: ["heavy crossbow"],
  },
  {
    dietyName: "Apollyon",
    category: "Horsemen",
    alignment: "NE",
    followerAlignments: ["LE", "NE", "CE"],
    divineFont: "harm",
    domains: ["Air", "Decay", "Plague", "Swarm"],
    favoredWeapon: ["scythe"],
  },
  {
    dietyName: "Charon",
    category: "Horsemen",
    alignment: "NE",
    followerAlignments: ["LE", "NE", "CE"],
    divineFont: "harm",
    domains: ["Death", "Knowledge", "Soul", "Water"],
    favoredWeapon: ["staff"],
  },
  {
    dietyName: "Szuriel",
    category: "Horsemen",
    alignment: "NE",
    followerAlignments: ["LE", "NE", "CE"],
    divineFont: "harm",
    domains: ["Ambition", "Destruction", "Fire", "Might"],
    favoredWeapon: ["greatsw", "d"],
  },
  {
    dietyName: "Trelmarixian",
    category: "Horsemen",
    alignment: "NE",
    followerAlignments: ["LE", "NE", "CE"],
    divineFont: "harm",
    domains: ["Decay", "Dust", "Earth", "Nightmares"],
    favoredWeapon: ["spiked gauntlet"],
  },
  {
    dietyName: "Barzahk",
    category: "Monitor Demigods",
    alignment: "N",
    followerAlignments: ["NG", "N", "CN"],
    divineFont: "heal",
    domains: ["Death", "Knowledge", "Travel", "Vigil"],
    favoredWeapon: ["club"],
  },
  {
    dietyName: "Chohar",
    category: "Old Sun Gods",
    alignment: "LG",
    followerAlignments: ["LG", "NG", "LN"],
    divineFont: "heal",
    domains: [
      "Cities",
      "Duty",
      "Family",
      "Fire",
      "Sun",
      "Toil",
      "Vigil",
      "Zeal",
    ],
    favoredWeapon: ["starknife"],
  },
  {
    dietyName: "Dajermube",
    category: "Old Sun Gods",
    alignment: "CG",
    followerAlignments: ["LG", "NG", "CG", "CN"],
    divineFont: "harm/heal",
    domains: [
      "Ambition",
      "Cities",
      "Freedom",
      "Freedom",
      "Moon",
      "Star",
      "Sun",
      "Zeal",
    ],
    favoredWeapon: ["greatpick"],
  },
  {
    dietyName: "Imot",
    category: "Monitor Demigods",
    alignment: "N",
    followerAlignments: ["LN", "N", "NE"],
    divineFont: "harm/heal",
    domains: ["Death", "Destruction", "Fate", "Glyph"],
    favoredWeapon: ["shield boss"],
  },
  {
    dietyName: "Kerkamoth",
    category: "Monitor Demigods",
    alignment: "LN",
    followerAlignments: ["LN", "N"],
    divineFont: "harm/heal",
    domains: ["Darkness", "Decay", "Destruction", "Void"],
    favoredWeapon: ["warhammer"],
  },
  {
    dietyName: "Luhar",
    category: "Old Sun Gods",
    alignment: "LN",
    followerAlignments: ["LG", "LN", "LE"],
    divineFont: "harm",
    domains: [
      "Cities",
      "Darkness",
      "Dreams",
      "Fate",
      "Soul",
      "Star",
      "Sun",
      "Zeal",
    ],
    favoredWeapon: ["spiked chain"],
  },
  {
    dietyName: "Monad",
    category: "Monitor Demigods",
    alignment: "N",
    followerAlignments: ["LN", "N"],
    divineFont: "harm/heal",
    domains: ["Creation", "Knowledge", "Truth", "Void"],
    favoredWeapon: ["fist"],
  },
  {
    dietyName: "Mother Vulture",
    category: "Monitor Demigods",
    alignment: "N",
    followerAlignments: ["NG", "N", "NE"],
    divineFont: "heal",
    domains: ["Change", "Death", "Decay", "Nature"],
    favoredWeapon: ["sickle"],
  },
  {
    dietyName: "Narakaas",
    category: "Monitor Demigods",
    alignment: "N",
    followerAlignments: ["NG", "LN", "N"],
    divineFont: "heal",
    domains: ["Change", "Death", "Pain", "Sorrow"],
    favoredWeapon: ["greataxe"],
  },
  {
    dietyName: "Narriseminek",
    category: "Monitor Demigods",
    alignment: "CN",
    followerAlignments: ["CG", "CN"],
    divineFont: "harm/heal",
    domains: ["Delirium", "Freedom", "Knowledge", "Perfection"],
    favoredWeapon: ["hatchet"],
  },
  {
    dietyName: "Otolmens",
    category: "Monitor Demigods",
    alignment: "LN",
    followerAlignments: ["LG", "LN"],
    divineFont: "heal",
    domains: ["Creation", "Fate", "Knowledge", "Perfection"],
    favoredWeapon: ["mace"],
  },
  {
    dietyName: "Saloc",
    category: "Monitor Demigods",
    alignment: "N",
    followerAlignments: ["NG", "N", "NE"],
    divineFont: "heal",
    domains: ["Change", "Death", "Freedom", "Knowledge"],
    favoredWeapon: ["guisarme"],
  },
  {
    dietyName: "Tlehar",
    category: "Old Sun Gods",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG"],
    divineFont: "heal",
    domains: [
      "Change",
      "Cities",
      "Creation",
      "Healing",
      "Passion",
      "Sun",
      "Vigil",
      "Zeal",
    ],
    favoredWeapon: ["m", "ningstar"],
  },
  {
    dietyName: "Valmallos",
    category: "Monitor Demigods",
    alignment: "LN",
    followerAlignments: ["LG", "LN"],
    divineFont: "harm/heal",
    domains: ["Fate", "Glyph", "Knowledge", "Magic"],
    favoredWeapon: ["kukri"],
  },
  {
    dietyName: "Ydajisk",
    category: "Monitor Demigods",
    alignment: "CN",
    followerAlignments: ["CG", "CN", "CE"],
    divineFont: "harm/heal",
    domains: ["Change", "Glyph", "Knowledge", "Trickery"],
    favoredWeapon: ["jaws", "greatclub"],
  },
  {
    dietyName: "Azathoth",
    category: "Outer Gods and Great Old Ones",
    alignment: "CN",
    followerAlignments: ["CN", "CE"],
    divineFont: "harm",
    domains: ["Decay", "Destruction", "Nightmares", "Void"],
    favoredWeapon: ["warhammer"],
  },
  {
    dietyName: "Hastur",
    category: "Outer Gods and Great Old Ones",
    alignment: "CE",
    followerAlignments: ["NE", "CE"],
    divineFont: "harm",
    domains: ["Glyph", "Secrecy", "Void", "Wealth"],
    favoredWeapon: ["rapier"],
  },
  {
    dietyName: "Nhimbaloth",
    category: "Outer Gods and Great Old Ones",
    alignment: "CE",
    followerAlignments: ["CE"],
    divineFont: "harm",
    domains: ["Abomination", "Decay", "Delirium", "Nature", "Undeath", "Void"],
    favoredWeapon: ["flail"],
  },
  {
    dietyName: "Nyarlathotep (Haunter in the Dark)",
    category: "Outer Gods and Great Old Ones",
    alignment: "CE",
    followerAlignments: ["NE", "CE"],
    divineFont: "harm",
    domains: ["Darkness", "Knowledge", "Nightmares", "Trickery"],
    favoredWeapon: ["kukri"],
  },
  {
    dietyName: "Nyarlathotep (The Crawling Chaos)",
    category: "Outer Gods and Great Old Ones",
    alignment: "CE",
    followerAlignments: ["NE", "CE"],
    divineFont: "harm",
    domains: ["Knowledge", "Magic", "Nightmares", "Trickery"],
    favoredWeapon: ["staff"],
  },
  {
    dietyName: "Xhamen-Dor",
    category: "Outer Gods and Great Old Ones",
    alignment: "NE",
    followerAlignments: ["NE", "CE"],
    divineFont: "harm",
    domains: ["Change", "Decay", "Dreams", "Nature"],
    favoredWeapon: ["spear"],
  },
  {
    dietyName: "Yog-Sothoth",
    category: "Outer Gods and Great Old Ones",
    alignment: "CN",
    followerAlignments: ["CN", "CE"],
    divineFont: "harm",
    domains: ["Knowledge", "Time", "Travel", "Void"],
    favoredWeapon: ["dagger"],
  },
  {
    dietyName: "Cosmic Caravan",
    category: "Pantheons",
    alignment: "CG",
    followerAlignments: ["NG", "CG", "CN"],
    divineFont: "harm/heal",
    domains: ["Darkness", "Fate", "Freedom", "Moon", "Star", "Void"],
    favoredWeapon: ["starknife"],
  },
  {
    dietyName: "Demon Bringers",
    category: "Pantheons",
    alignment: "LG",
    followerAlignments: ["LG", "NG", "CG", "LN"],
    divineFont: "heal",
    domains: ["Cities", "Creation", "Duty", "Family", "Might", "Protection"],
    favoredWeapon: ["khopesh"],
  },
  {
    dietyName: "Dwarven Pantheon",
    category: "Pantheons",
    alignment: "LG",
    followerAlignments: ["LG", "NG", "LN", "N"],
    divineFont: "heal",
    domains: ["Creation", "Duty", "Family", "Glyph", "Protection", "Wealth"],
    favoredWeapon: ["warhammer"],
  },
  {
    dietyName: "Elven Pantheon",
    category: "Pantheons",
    alignment: "CG",
    followerAlignments: ["NG", "CG", "CN"],
    divineFont: "heal",
    domains: ["Creation", "Magic", "Moon", "Nature"],
    favoredWeapon: ["longbow", "sh", "tbow"],
  },
  {
    dietyName: "Pillars of Knowledge",
    category: "Pantheons",
    alignment: "N",
    followerAlignments: ["LN", "N", "CN"],
    divineFont: "harm/heal",
    domains: [
      "Creation",
      "Glyph",
      "Knowledge",
      "Perfection",
      "Secrecy",
      "Time",
      "Truth",
    ],
    favoredWeapon: ["light hammer"],
  },
  {
    dietyName: "Sky Keepers",
    category: "Pantheons",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG"],
    divineFont: "heal",
    domains: ["Air", "Change", "Freedom", "Lightning", "Protection", "Wyrmkin"],
    favoredWeapon: ["longbow"],
  },
  {
    dietyName: "The Freeing Flame",
    category: "Pantheons",
    alignment: "CN",
    followerAlignments: ["NG", "CG", "N", "CN"],
    divineFont: "harm/heal",
    domains: [
      "Ambition",
      "Change",
      "Destruction",
      "Freedom",
      "Might",
      "Protection",
      "Zeal",
    ],
    favoredWeapon: ["sw", "d cane"],
  },
  {
    dietyName: "The Godclaw",
    category: "Pantheons",
    alignment: "LN",
    followerAlignments: ["LG", "LN", "LE"],
    divineFont: "harm/heal",
    domains: ["Duty", "Perfection", "Protection", "Tyranny", "Zeal"],
    favoredWeapon: ["m", "ningstar"],
  },
  {
    dietyName: "The Path of the Heavens",
    category: "Pantheons",
    alignment: "CG",
    followerAlignments: ["NG", "CG", "CN"],
    divineFont: "heal",
    domains: ["Moon", "Star", "Sun", "Toil", "Travel", "Void"],
    favoredWeapon: ["starknife"],
  },
  {
    dietyName: "The Prismatic Ray",
    category: "Pantheons",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG"],
    divineFont: "heal",
    domains: [
      "Creation",
      "Family",
      "Healing",
      "Moon",
      "Protection",
      "Sun",
      "Travel",
    ],
    favoredWeapon: ["sh", "tsw", "d"],
  },
  {
    dietyName: "Touch of the Sun",
    category: "Pantheons",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG", "LN"],
    divineFont: "heal",
    domains: ["Change", "Family", "Healing", "Passion", "Sun", "Vigil", "Zeal"],
    favoredWeapon: ["rapier"],
  },
  {
    dietyName: "Wards of the Pharaoh",
    category: "Pantheons",
    alignment: "NG",
    followerAlignments: ["NG", "CG", "LN", "N"],
    divineFont: "harm/heal",
    domains: ["Family", "Glyph", "Healing", "Knowledge", "Magic", "Protection"],
    favoredWeapon: ["staff"],
  },
  {
    dietyName: "Ardad Lili",
    category: "Queens of the Night",
    alignment: "LE",
    followerAlignments: ["LN", "LE", "NE"],
    divineFont: "harm",
    domains: ["Creation", "Darkness", "Passion", "Wyrmkin"],
    favoredWeapon: ["dagger"],
  },
  {
    dietyName: "Doloras",
    category: "Queens of the Night",
    alignment: "LE",
    followerAlignments: ["LE", "NE"],
    divineFont: "harm",
    domains: ["Creation", "Pain", "Repose", "Sorrow"],
    favoredWeapon: ["kukri"],
  },
  {
    dietyName: "Eiseth",
    category: "Queens of the Night",
    alignment: "LE",
    followerAlignments: ["LE"],
    divineFont: "harm",
    domains: ["Ambition", "Destruction", "Might", "Zeal"],
    favoredWeapon: ["longbow"],
  },
  {
    dietyName: "Mahathallah",
    category: "Queens of the Night",
    alignment: "LE",
    followerAlignments: ["LN", "LE", "NE"],
    divineFont: "harm",
    domains: ["Fate", "Trickery", "Truth", "Undeath"],
    favoredWeapon: ["bola"],
  },
  {
    dietyName: "Alglenweis",
    category: "Sarkorian Gods",
    alignment: "CG",
    followerAlignments: ["NG", "CG", "CN"],
    divineFont: "heal",
    domains: ["Cold", "Creation", "Might", "Soul"],
    favoredWeapon: ["war flail"],
  },
  {
    dietyName: "Stag Mother of the Forest of Stones",
    category: "Sarkorian Gods",
    alignment: "N",
    followerAlignments: ["LG", "NG", "CG", "LN", "N", "CN", "LE", "NE"],
    divineFont: "heal",
    domains: ["Family", "Healing", "Nature", "Pain"],
    favoredWeapon: ["ranseur"],
  },
  {
    dietyName: "Sturovenen",
    category: "Sarkorian Gods",
    alignment: "LG",
    followerAlignments: ["LG", "NG", "LN"],
    divineFont: "heal",
    domains: ["Air", "Confidence", "Passion", "Sun"],
    favoredWeapon: ["main-gauche"],
  },
  {
    dietyName: "Daikitsu",
    category: "Tian Gods",
    alignment: "N",
    followerAlignments: ["NG", "LN", "N", "CN"],
    divineFont: "heal",
    domains: ["Change", "Creation", "Family", "Nature"],
    favoredWeapon: ["flail"],
  },
  {
    dietyName: "Fumeiyoshi",
    category: "Tian Gods",
    alignment: "NE",
    followerAlignments: ["LE", "NE", "CE"],
    divineFont: "harm",
    domains: ["Ambition", "Destruction", "Earth", "Undeath"],
    favoredWeapon: ["naginata"],
  },
  {
    dietyName: "General Susumu",
    category: "Tian Gods",
    alignment: "LE",
    followerAlignments: ["LN", "LE"],
    divineFont: "harm",
    domains: ["Confidence", "Destruction", "Might", "Zeal"],
    favoredWeapon: ["longbow"],
  },
  {
    dietyName: "Hei Feng",
    category: "Tian Gods",
    alignment: "CN",
    followerAlignments: ["CG", "CN", "CE"],
    divineFont: "harm/heal",
    domains: [
      "Air",
      "Destruction",
      "Indulgence",
      "Lightning",
      "Travel",
      "Water",
    ],
    favoredWeapon: ["nine-ring sw", "d"],
  },
  {
    dietyName: "Kofusachi",
    category: "Tian Gods",
    alignment: "CG",
    followerAlignments: ["NG", "CG"],
    divineFont: "heal",
    domains: ["Luck", "Passion", "Travel", "Wealth"],
    favoredWeapon: ["staff"],
  },
  {
    dietyName: "Lady Jingxi",
    category: "Tian Gods",
    alignment: "NG",
    followerAlignments: ["NG", "N"],
    divineFont: "heal",
    domains: ["Creation", "Glyph", "Knowledge", "Repose"],
    favoredWeapon: ["fighting fan"],
  },
  {
    dietyName: "Lady Nanbyo",
    category: "Tian Gods",
    alignment: "CE",
    followerAlignments: ["NE", "CE"],
    divineFont: "harm",
    domains: ["Destruction", "Fire", "Plague", "Water"],
    favoredWeapon: ["warhammer"],
  },
  {
    dietyName: "Lao Shu Po",
    category: "Tian Gods",
    alignment: "NE",
    followerAlignments: ["N", "LE", "NE", "CE"],
    divineFont: "harm",
    domains: ["Darkness", "Luck", "Swarm", "Trickery"],
    favoredWeapon: ["dagger"],
  },
  {
    dietyName: "Nalinivati",
    category: "Tian Gods",
    alignment: "N",
    followerAlignments: ["NG", "LN", "N", "NE"],
    divineFont: "harm/heal",
    domains: ["Glyph", "Magic", "Passion", "Wyrmkin"],
    favoredWeapon: ["jaws", "urumi"],
  },
  {
    dietyName: "Qi Zhong",
    category: "Tian Gods",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG", "N"],
    divineFont: "heal",
    domains: ["Healing", "Knowledge", "Magic", "Protection"],
    favoredWeapon: ["heavy mace"],
  },
  {
    dietyName: "Shizuru",
    category: "Tian Gods",
    alignment: "LG",
    followerAlignments: ["LG", "NG", "LN"],
    divineFont: "heal",
    domains: ["Duty", "Perfection", "Sorrow", "Sun", "Vigil"],
    favoredWeapon: ["katana"],
  },
  {
    dietyName: "Sun Wukong",
    category: "Tian Gods",
    alignment: "CN",
    followerAlignments: ["CG", "CN", "CE"],
    divineFont: "harm/heal",
    domains: ["Indulgence", "Might", "Nature", "Trickery"],
    favoredWeapon: ["bo staff"],
  },
  {
    dietyName: "Tsukiyo",
    category: "Tian Gods",
    alignment: "LG",
    followerAlignments: ["LG", "NG", "CG", "LN", "N"],
    divineFont: "heal",
    domains: ["Change", "Delirium", "Moon", "Repose", "Soul"],
    favoredWeapon: ["spear"],
  },
  {
    dietyName: "Yaezhing",
    category: "Tian Gods",
    alignment: "LE",
    followerAlignments: ["LE", "NE"],
    divineFont: "harm",
    domains: ["Death", "Duty", "Pain", "Trickery"],
    favoredWeapon: ["shuriken"],
  },
  {
    dietyName: "Yamatsumi",
    category: "Tian Gods",
    alignment: "N",
    followerAlignments: ["NG", "LN", "N", "CN"],
    divineFont: "harm/heal",
    domains: ["Cold", "Earth", "Fire", "Might"],
    favoredWeapon: ["greatclub"],
  },
  {
    dietyName: "Arundhat",
    category: "Vudrani Gods",
    alignment: "NG",
    followerAlignments: ["LG", "NG", "CG", "N"],
    divineFont: "heal",
    domains: ["Healing", "Magic", "Nature", "Protection"],
    favoredWeapon: ["staff"],
  },
  {
    dietyName: "Ashukharma",
    category: "Vudrani Gods",
    alignment: "CN",
    followerAlignments: ["CG", "N", "CN"],
    divineFont: "harm/heal",
    domains: ["Earth", "Might", "Protection", "Repose"],
    favoredWeapon: ["greatsw", "d"],
  },
  {
    dietyName: "Chamidu",
    category: "Vudrani Gods",
    alignment: "N",
    followerAlignments: ["NG", "N", "NE"],
    divineFont: "harm/heal",
    domains: ["Healing", "Lightning", "Nature", "Nightmares"],
    favoredWeapon: ["spear"],
  },
  {
    dietyName: "Dhalavei",
    category: "Vudrani Gods",
    alignment: "LE",
    followerAlignments: ["LE", "NE"],
    divineFont: "harm/heal",
    domains: ["Destruction", "Knowledge", "Secrecy", "Trickery"],
    favoredWeapon: ["temple sw", "d"],
  },
  {
    dietyName: "Diomazul",
    category: "Vudrani Gods",
    alignment: "LE",
    followerAlignments: ["LN", "LE"],
    divineFont: "harm/heal",
    domains: ["Destruction", "Earth", "Water", "Zeal"],
    favoredWeapon: ["scimitar"],
  },
  {
    dietyName: "Gruhastha",
    category: "Vudrani Gods",
    alignment: "LG",
    followerAlignments: ["LG", "NG"],
    divineFont: "heal",
    domains: ["Glyph", "Knowledge", "Nature", "Perfection", "Travel", "Truth"],
    favoredWeapon: ["sh", "tbow"],
  },
  {
    dietyName: "Lahkgya",
    category: "Vudrani Gods",
    alignment: "CE",
    followerAlignments: ["CE"],
    divineFont: "harm",
    domains: ["Indulgence", "Nature", "Swarm", "Trickery"],
    favoredWeapon: ["jaws", "battle axe"],
  },
  {
    dietyName: "Likha",
    category: "Vudrani Gods",
    alignment: "N",
    followerAlignments: ["NG", "LN", "N", "CN"],
    divineFont: "harm/heal",
    domains: ["Creation", "Knowledge", "Passion", "Sorrow"],
    favoredWeapon: ["hatchet"],
  },
  {
    dietyName: "Matravash",
    category: "Vudrani Gods",
    alignment: "LN",
    followerAlignments: ["LG", "LN", "N"],
    divineFont: "heal",
    domains: ["Cities", "Nature", "Travel", "Water"],
    favoredWeapon: ["whip"],
  },
  {
    dietyName: "Ragdya",
    category: "Vudrani Gods",
    alignment: "N",
    followerAlignments: ["NG", "LN", "N", "CN"],
    divineFont: "heal",
    domains: ["Air", "Confidence", "Might", "Perfection"],
    favoredWeapon: ["mace"],
  },
  {
    dietyName: "Raumya",
    category: "Vudrani Gods",
    alignment: "NE",
    followerAlignments: ["NG", "N", "LE", "NE"],
    divineFont: "harm/heal",
    domains: ["Confidence", "Knowledge", "Might", "Wealth"],
    favoredWeapon: ["trident"],
  },
];
